apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysqldb
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: timesheet-secret
                  key: mysql-rootpwd
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: timesheet-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: timesheet-secret
                  key: mysql-password
            - name: MYSQL_DATABASE
              value: "timeSheetDevOps"
            - name: MYSQL_ROOT_HOST
              value: "%"
---
apiVersion: v1
kind: Service
metadata:
  name: timesheet-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
